const fs = require("node:fs")
/*
const exampleData = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

const data = exampleData.split("\n");
*/

const data = fs.readFileSync("./day7data.txt").toString().split("\n")

let splits = 0;

let beams = new Array(data[0].length).fill(0);
beams[data[0].indexOf("S")] = 1;

for (let i=1;i<data.length;i++) {
    for (let x=0;x<data[i].length;x++) {
        if (data[i][x] == "^" && beams[x] > 0) {
            beams[x-1] += beams[x];
            beams[x+1] += beams[x];
            beams[x] = 0;
        }
    }
}

const sum = beams.reduce((acc, val) => acc += val)

console.log(sum);